//apps/models/DND_books

module.exports = {
				AN :       	"FR3 Anauroch:The Empire of Shade",
                AE :        "Arms and Equipment Guide",
                BFK :      	"Barrow of the Forgotten King",
                BB :        "Bastion of Broken Souls",
                BC :        "Book of Challenges",
                BE :        "Book of Exalted Deeds",
                BV :        "Book of Vile Darkness",
                CR :        "Champions of Ruin",
                CV :        "Champions of Valor",
                CIP :       "City of Peril",
                COS :     	"City of Splendors:Waterdeep",
                CSQ :     	"City of the Spider Queen",
                CI :        "Cityscape",
                CAd :     	"Complete Adventurer",
                CAR :      	"Complete Arcane",
                CC :        "Complete Champion",
                CD :        "Complete Divine",
                CM :       	"Complete Mage",
                CP :        "Complete Psionic",
                CS :        "Complete Scoundrel",
                CW :       	"Complete Warrior",
                CO :        "Cormyr: The Tearing of the Weave",
                DG :        "D&D Gazetteer",
                DH :        "Deep Horizon",
                DF :        "Defenders of the Faith",
                DD :        "Deities and Demigods",
                DR :        "Draconomicon",
                DM :       	"Dragon Magic",
                DCS :      	"Dragonlance Campaign Setting",
                DRA :       "Dragonmarked",
                DE :        "Dragons of Eberron",
                DRF :       "Dragons of Faerûn",
                DRU :      	"Drow of the Underdark",
                DMG :   	"Dungeon Master's Guide (3.5)",
                DMG2 : 		"Dungeon Master's Guide II",
                DU :        "Dungeonscape",
                ECS :       "Eberron Campaign Setting",
                ELE :       "Elder Evils",
                EA :        "Enemies and Allies",
                EL :        "Epic Level Handbook",
                EE :        "Exemplars of Evil",
                XPH :      	"Expanded Psionics Handbook",
                RAV :       "Expedition to Castle Ravenloft",
                EDP :      	"Expedition to the Demonweb Pits",
                ERG :      	"Expedition to the Ruins of Greyhawk",
                EU :        "Expedition to Undermountain",
                EH :        "Explorer's Handbook",
                ELQ :      	"Eyes of the Lich Queen",
                FP :        "Faiths and Pantheons",
                FE :        "Faiths of Eberron",
                FLFD :     	"Fantastic Locations:Fane of the Drow",
                FLFR :      "Fantastic Locations:Fields of Ruin",
                FLHP :     	"Fantastic Locations:Hellspike Prison",
                FF :        "Fiend Folio",
                FCI :       "Fiendish Codex I",
                FCII :      "Fiendish Codex II",
                FO :        "The Forge of Fury",
                FW :        "The Forge of War",
                FRCS :     	"Forgotten Realms Campaign Setting",
                FY :        "Fortress of the Yuan-Ti",
                FR :        "Frostburn",
                GH :        "Ghostwalk",
                GHR :      	"Grand History of the Realms",
                GC :        "Grasp of the Emerald Claw",
                HN :        "Heart of Nightfang Spire",
                HBG :      	"Hero Builder's Guidebook",
                HB :        "Heroes of Battle",
                HH :        "Heroes of Horror",
                LM :        "Libris Mortis",
                LG :        "Living Greyhawk Gazetteer",
                LF :        "Lord of the Iron Fortress",
                LD :        "Lords of Darkness",
                LOM :      	"Lords of Madness",
                LE :        "Lost Empires of Faerûn",
                MIC :       "Magic Item Compendium",
                MOE :      	"Magic of Eberron",
                MAG :      	"Magic of Faerûn",
                MOI :       "Magic of Incarnum",
                MP :        "Manual of the Planes",
                MW :      	"Masters of the Wild",
                MH :        "Miniatures Handbook",
                MON :     	"Monster Compendium: Monsters of Faerûn",
                MM :      	"Monster Manual",
                MM2 :    	"Monster Manual II",
                MM3 :    	"Monster Manual III",
                MM4 :    	"Monster Manual IV",
                MM5 :    	"Monster Manual V",
                MYS :      	"Mysteries of the Moonsea",
                OA :        "Oriental Adventures",
                PLH :       "Planar Handbook",
                PE :        "Player's Guide to Eberron",
                PG :        "Player's Guide to Faerûn",
                PHB :        "Player's Handbook",
                PH2 :       "Player's Handbook II",
                PF :        "Power of Faerûn",
                RD :        "Races of Destiny",
                RE :        "Races of Eberron",
                RAC :       "Races of Faerûn",
                RS :        "Races of Stone",
                RW :        "Races of the Wild",
                RH :        "Red Hand of Doom",
                RT :        "Return to the Temple of Elemental Evil",
                RC :        "Rules Compendium",
                Sa :        "Sandstorm",
                SS :        "Savage Species",
                SOS :       "Secrets of Sarlona",
                SX :        "Secrets of Xen’drik",
                SK :        "Serpent Kingdoms",
                SSL :       "FR2 Shadowdale:The Scouring of the Land",
                SL :        "Shadows of the Last War",
                SH :        "Sharn:City of Towers",
                SHG :       "The Shattered Gates of Slaughtergarde",
                SHS :       "Shining South",
                SM :        "Silver Marches",
                SIS :       "The Sinister Spire",
                SAS :       "Song and Silence: A Guidebook to Bards and Rogues",
                SG :        "Sons of Gruumsh",
                SD :        "The Speaker in Dreams",
                STS :       "The Standing Stone",
                SB :        "Stronghold Builder's Guidebook",
                SC :        "Spell Compendium",
                SF :        "Sword and Fist: A Guidebook to Monks and Fighters",
                TB :        "Tome and Blood: A Guidebook to Wizards and Sorcerers",
                TOB :       "Tome of Battle: The Book of Nine Swords",
                TM :        "Tome of Magic",
                UNA :       "Unapproachable East",
                UND :      	"Underdark",
                UA :        "Unearthed Arcana",
                VGD :      	"Voyage of the Golden Dragon",
                WB :        "Whispers of the Vampire's Blade"

};